const escape = value => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
const money = (cents, currency = "EUR") => new Intl.NumberFormat("fr-BE", { style: "currency", currency }).format(Number(cents || 0) / 100);
export function renderInvoiceEmail({ order, items, address, company = {}, orderUrl, siteUrl, heading = "Merci pour votre commande !", intro = "Votre paiement est confirmé.", extraHtml = "" }) {
  const name = escape(company.name || "Hormones & Harmonie");
  const rows = items.map(item => `<tr><td style="padding:12px 6px;border-bottom:1px solid #eadfe2">${escape(item.product_name)}</td><td style="padding:12px 6px;text-align:center">${Number(item.quantity)}</td><td style="padding:12px 6px;text-align:right;white-space:nowrap">${money(item.unit_price, order.currency)}</td><td style="padding:12px 6px;text-align:right;white-space:nowrap">${money(item.line_total, order.currency)}</td></tr>`).join("");
  const details = [company.address, company.enterprise_number ? `N° d’entreprise : ${company.enterprise_number}` : "", company.phone ? `Tél. : ${company.phone}` : "", company.email].filter(Boolean).map(escape).join("<br>");
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Votre commande — ${name}</title></head>
<body style="margin:0;background:#f5efea;font-family:Arial,sans-serif;color:#493333"><table role="presentation" width="100%"><tr><td align="center" style="padding:24px 10px"><table role="presentation" width="100%" style="max-width:620px;background:#fff;border-radius:16px;overflow:hidden">
<tr><td style="padding:30px 20px;background:#a47788;text-align:center;color:white"><h1 style="margin:0;font-size:26px">${name}</h1></td></tr>
<tr><td style="padding:26px 20px"><h2 style="font-size:23px;margin:0 0 14px">${escape(heading)}</h2><p>${escape(intro)}</p>${extraHtml}<p style="overflow-wrap:anywhere">Commande ${escape(order.order_number || order.id)}<br>${escape(new Date(order.created_at).toLocaleString("fr-BE"))}</p><p><strong>${escape(address?.full_name)}</strong><br>${escape(address?.email)}<br>${escape(address?.address1)}<br>${escape(address?.address2)}<br>${escape(address?.postal_code)} ${escape(address?.city)}<br>${escape(address?.country)}</p>
<table width="100%" style="border-collapse:collapse;font-size:14px"><thead><tr><th align="left">Article</th><th>Qté</th><th align="right">Prix</th><th align="right">Total</th></tr></thead><tbody>${rows}</tbody></table>
<table width="100%" style="margin-top:20px;line-height:1.9"><tr><td>Sous-total</td><td align="right">${money(order.subtotal_amount, order.currency)}</td></tr><tr><td>Réduction</td><td align="right">− ${money(order.discount_amount, order.currency)}</td></tr><tr><td>Livraison</td><td align="right">${money(order.shipping_amount, order.currency)}</td></tr><tr><td><strong>Total</strong></td><td align="right"><strong>${money(order.total_amount, order.currency)}</strong></td></tr></table>
${orderUrl ? `<p style="text-align:center;margin:28px 0"><a href="${escape(orderUrl)}" style="display:inline-block;background:#a47788;color:#fff;padding:14px 24px;border-radius:8px;text-decoration:none;font-weight:bold">Voir sur le site</a></p><p style="font-size:13px;color:#736364">Ce lien privé vous permet de consulter votre commande et son suivi de livraison. Conservez cet email.</p>` : ""}</td></tr>
<tr><td style="padding:24px 20px;border-top:1px solid #eadfe2;text-align:center;font-size:14px;line-height:1.8"><strong>${name}</strong><br>${details}<br><a href="${escape(siteUrl)}" style="color:#a47788">${escape(siteUrl)}</a></td></tr></table></td></tr></table></body></html>`;
}
