name: Build H&H

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Installer les dependances frontend
        working-directory: ./client
        run: npm ci

      - name: Build du frontend
        working-directory: ./client
        env:
            VITE_API_URL: ${{ vars.VITE_API_URL }}
            VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}
            VITE_STRIPE_PUBLISHABLE_KEY: ${{ vars.VITE_STRIPE_PUBLISHABLE_KEY }}
            VITE_GOOGLE_MAPS_KEY: ${{ vars.VITE_GOOGLE_MAPS_KEY }}
            VITE_GOOGLE_MAPS_MAP_ID: ${{ vars.VITE_GOOGLE_MAPS_MAP_ID }}
            VITE_MR_BRAND_CODE: ${{ vars.VITE_MR_BRAND_CODE }}
            VITE_MR_ENSEIGNE: ${{ vars.VITE_MR_ENSEIGNE }}
        run: npm run build

      - name: Copier le build dans API
        run: |
          rm -rf ./api/dist
          cp -r ./client/dist ./api/dist

      - name: Verifier le resultat
        run: |
          echo "Contenu de api/dist :"
          ls -la ./api/dist